export const JWT_AUTH_SERVICE = 'JWT_AUTH_SERVICE';
export const PASSWORD_HASHER = 'PASSWORD_HASHER';
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const GOOGLE_OAUTH_SERVICE = 'GOOGLE_OAUTH_SERVICE';
export const FACEBOOK_OAUTH_SERVICE = 'FACEBOOK_OAUTH_SERVICE';

export const LOGIN_USE_CASE = 'LOGIN_USE_CASE';
export const SIGNUP_USE_CASE = 'SIGNUP_USE_CASE';
export const GOOGLE_LOGIN_USE_CASE = 'GOOGLE_LOGIN_USE_CASE';
export const FACEBOOK_LOGIN_USE_CASE = 'FACEBOOK_LOGIN_USE_CASE';
export const REFRESH_TOKEN_USE_CASE = 'REFRESH_TOKEN_USE_CASE';
export const VERIFY_EMAIL_USE_CASE = 'VERIFY_EMAIL_USE_CASE';
export const RESEND_OTP_USE_CASE = 'RESEND_OTP_USE_CASE';
export const FORGOT_PASSWORD_USE_CASE = 'FORGOT_PASSWORD_USE_CASE';
export const RESET_PASSWORD_USE_CASE = 'RESET_PASSWORD_USE_CASE';

export const OTP_REPOSITORY = 'OTP_REPOSITORY';     
export const OTP_SERVICE = 'OTP_SERVICE';        
export const EMAIL_SERVICE = 'EMAIL_SERVICE';      