export enum KSACities {
  RIYADH = 'riyadh',
  JEDDAH = 'jeddah',
  MECCA = 'mecca',
  MEDINA = 'medina',
  DAMMAM = 'dammam',
  KHOBAR = 'khobar',
  DHAHRAN = 'dhahran',
  TAIF = 'taif',
  TABUK = 'tabuk',
  BURAIDAH = 'buraidah',
  KHAMIS_MUSHAIT = 'khamis_mushait',
  HAIL = 'hail',
  NAJRAN = 'najran',
  HOFUF = 'hofuf',
  JUBAIL = 'jubail',
  ABHA = 'abha',
  YANBU = 'yanbu',
  QATIF = 'qatif',
  AL_KHARJ = 'al_kharj',
  AL_HASA = 'al_hasa',
  JIZAN = 'jizan',
  ARAR = 'arar',
  SAKAKA = 'sakaka',
  AL_BAHAH = 'al_bahah',
  BISHA = 'bisha',
  QURAYYAT = 'qurayyat',
  AR_RASS = 'ar_rass',
  UNAIZAH = 'unaizah',
  AL_MAJMAAH = 'al_majmaah',
  AL_QUNFUDHAH = 'al_qunfudhah',
}

export const allKsaCities = [
  'riyadh',
  'jeddah',
  'mecca',
  'medina',
  'dammam',
  'khobar',
  'dhahran',
  'taif',
  'tabuk',
  'buraidah',
  'khamis_mushait',
  'hail',
  'najran',
  'hofuf',
  'jubail',
  'abha',
  'yanbu',
  'qatif',
  'al_kharj',
  'al_hasa',
  'jizan',
  'arar',
  'sakaka',
  'al_bahah',
  'bisha',
  'qurayyat',
  'ar_rass',
  'unaizah',
  'al_majmaah',
  'al_qunfudhah',
];
