
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const PAYMENT_GATEWAY_FACTORY = 'PAYMENT_GATEWAY_FACTORY';
export const CREATE_PAYMENT_USE_CASE = 'CREATE_PAYMENT_USE_CASE';
export const PROCESS_WEBHOOK_USE_CASE = 'PROCESS_WEBHOOK_USE_CASE';